name: Python Sentry Testing Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Run setup script
      run: |
        python setup.py
        
    - name: Static analysis checks
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Create static assets
      run: |
        mkdir -p static
        echo "/* Sentry Testing Zone static assets */" > static/styles.css
        
    - name: Prepare for GitHub Pages
      run: |
        mkdir -p _site
        cp -r templates static _site/
        cp app.py requirements.txt setup.py _site/
        
        # Create a simple index.html for GitHub Pages that redirects to the Flask app
        cat > _site/index.html << 'EOL'
        <!DOCTYPE html>
        <html>
        <head>
          <meta charset="UTF-8">
          <meta http-equiv="refresh" content="0;url=https://sentry-testing-zone.onrender.com/">
          <title>Redirecting to Sentry Testing Zone</title>
        </head>
        <body>
          <p>This project requires a Python server to run.</p>
          <p>Redirecting to the deployed version at <a href="https://sentry-testing-zone.onrender.com/">https://sentry-testing-zone.onrender.com/</a>...</p>
          <script>
            window.location.href = "https://sentry-testing-zone.onrender.com/";
          </script>
        </body>
        </html>
        EOL
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
